title: Kshitij Aggarwal
description: Data Scientist | PhD in Physics and Astronomy
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - old/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _posts/
  - images/